spring.application.name=caresapo

riot.api.key=${RiotApiKey}

twitch.client.id=${TwitchClientId}
twitch.client.secret=${TwitchClientSecret}

front.allowed.url=${FrontAllowedUrl}

server.port=${PORT:8080}
